service: graphql-api

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["NamesDynamoDBTable", "Arn" ] }
  environment:
    NAMES_TABLE: { "Ref": "NamesDynamoDBTable" }

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get

resources:
  Resources:
    NamesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: firstName
            AttributeType: S
        KeySchema:
          -
            AttributeName: firstName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1